-- Sonora - Full Supabase schema
-- Apply in Supabase SQL Editor (new project / clean schema recommended).

-- =====================================================
-- Extensions
-- =====================================================
create extension if not exists pgcrypto;

-- =====================================================
-- Utility function for updated_at
-- =====================================================
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- =====================================================
-- Core tables
-- =====================================================
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  handle text not null,
  bio text,
  avatar_url text,
  cover_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_handle_format check (left(handle, 1) = '@')
);

create unique index if not exists profiles_handle_unique_ci
  on public.profiles (lower(handle));

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  content text,
  spotify_url text,
  spotify_type text,
  media_url text,
  media_type text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists posts_user_id_created_at_idx
  on public.posts (user_id, created_at desc);

create table if not exists public.post_likes (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint post_likes_unique unique (post_id, user_id)
);

create index if not exists post_likes_user_id_idx
  on public.post_likes (user_id);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists comments_post_id_created_at_idx
  on public.comments (post_id, created_at asc);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now(),
  constraint messages_sender_receiver_diff check (sender_id <> receiver_id)
);

create index if not exists messages_sender_receiver_created_idx
  on public.messages (sender_id, receiver_id, created_at desc);

create index if not exists messages_receiver_sender_created_idx
  on public.messages (receiver_id, sender_id, created_at desc);

create table if not exists public.communities (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text,
  created_by uuid not null references public.profiles(id) on delete cascade,
  genre text,
  is_public boolean not null default true,
  avatar_url text,
  cover_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists communities_created_by_idx
  on public.communities (created_by);

create table if not exists public.community_members (
  id bigint generated by default as identity primary key,
  community_id uuid not null references public.communities(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint community_members_unique unique (community_id, user_id)
);

create index if not exists community_members_user_idx
  on public.community_members (user_id);

create table if not exists public.community_posts (
  id bigint generated by default as identity primary key,
  community_id uuid not null references public.communities(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  post_type text,
  title text,
  spotify_url text,
  image_url text,
  album text,
  track_number text,
  content text,
  likes_count integer not null default 0,
  shares_count integer not null default 0,
  saves_count integer not null default 0,
  comments jsonb not null default '[]'::jsonb,
  poll_options jsonb not null default '[]'::jsonb,
  poll_votes jsonb not null default '{}'::jsonb,
  poll_total_votes integer not null default 0,
  challenge_entries jsonb not null default '[]'::jsonb,
  challenge_unit text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint community_posts_comments_is_array check (jsonb_typeof(comments) = 'array'),
  constraint community_posts_poll_options_is_array check (jsonb_typeof(poll_options) = 'array'),
  constraint community_posts_poll_votes_is_object check (jsonb_typeof(poll_votes) = 'object'),
  constraint community_posts_challenge_entries_is_array check (jsonb_typeof(challenge_entries) = 'array')
);

create index if not exists community_posts_community_created_idx
  on public.community_posts (community_id, created_at desc);

create index if not exists community_posts_user_created_idx
  on public.community_posts (user_id, created_at desc);

create table if not exists public.playlists (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  description text,
  spotify_url text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists playlists_user_created_idx
  on public.playlists (user_id, created_at desc);

create table if not exists public.ascensao_posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text,
  content text,
  post_kind text not null default 'video',
  media_url text not null,
  likes_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ascensao_posts_kind_check check (post_kind in ('video', 'audio', 'youtube'))
);

create index if not exists ascensao_posts_user_created_idx
  on public.ascensao_posts (user_id, created_at desc);

create table if not exists public.user_follows (
  id bigint generated by default as identity primary key,
  follower_id uuid not null references public.profiles(id) on delete cascade,
  following_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint user_follows_unique unique (follower_id, following_id),
  constraint user_follows_diff check (follower_id <> following_id)
);

create index if not exists user_follows_follower_idx
  on public.user_follows (follower_id);

create index if not exists user_follows_following_idx
  on public.user_follows (following_id);

-- =====================================================
-- Triggers
-- =====================================================
drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists trg_posts_updated_at on public.posts;
create trigger trg_posts_updated_at
before update on public.posts
for each row execute function public.set_updated_at();

drop trigger if exists trg_comments_updated_at on public.comments;
create trigger trg_comments_updated_at
before update on public.comments
for each row execute function public.set_updated_at();

drop trigger if exists trg_communities_updated_at on public.communities;
create trigger trg_communities_updated_at
before update on public.communities
for each row execute function public.set_updated_at();

drop trigger if exists trg_community_posts_updated_at on public.community_posts;
create trigger trg_community_posts_updated_at
before update on public.community_posts
for each row execute function public.set_updated_at();

drop trigger if exists trg_playlists_updated_at on public.playlists;
create trigger trg_playlists_updated_at
before update on public.playlists
for each row execute function public.set_updated_at();

drop trigger if exists trg_ascensao_posts_updated_at on public.ascensao_posts;
create trigger trg_ascensao_posts_updated_at
before update on public.ascensao_posts
for each row execute function public.set_updated_at();

-- =====================================================
-- Realtime publication (needed by feed/direct/playlists live updates)
-- =====================================================
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'posts') then
      execute 'alter publication supabase_realtime add table public.posts';
    end if;
    if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'messages') then
      execute 'alter publication supabase_realtime add table public.messages';
    end if;
    if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'playlists') then
      execute 'alter publication supabase_realtime add table public.playlists';
    end if;
  end if;
end $$;

-- =====================================================
-- RLS
-- =====================================================
alter table public.profiles enable row level security;
alter table public.posts enable row level security;
alter table public.post_likes enable row level security;
alter table public.comments enable row level security;
alter table public.messages enable row level security;
alter table public.communities enable row level security;
alter table public.community_members enable row level security;
alter table public.community_posts enable row level security;
alter table public.playlists enable row level security;
alter table public.ascensao_posts enable row level security;
alter table public.user_follows enable row level security;

-- profiles
drop policy if exists profiles_select_authenticated on public.profiles;
create policy profiles_select_authenticated
on public.profiles
for select
to authenticated
using (true);

drop policy if exists profiles_insert_self on public.profiles;
create policy profiles_insert_self
on public.profiles
for insert
to authenticated
with check (id = auth.uid());

drop policy if exists profiles_update_self on public.profiles;
create policy profiles_update_self
on public.profiles
for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

drop policy if exists profiles_delete_self on public.profiles;
create policy profiles_delete_self
on public.profiles
for delete
to authenticated
using (id = auth.uid());

-- posts
drop policy if exists posts_select_authenticated on public.posts;
create policy posts_select_authenticated
on public.posts
for select
to authenticated
using (true);

drop policy if exists posts_insert_owner on public.posts;
create policy posts_insert_owner
on public.posts
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists posts_update_owner on public.posts;
create policy posts_update_owner
on public.posts
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists posts_delete_owner on public.posts;
create policy posts_delete_owner
on public.posts
for delete
to authenticated
using (user_id = auth.uid());

-- post_likes
drop policy if exists post_likes_select_authenticated on public.post_likes;
create policy post_likes_select_authenticated
on public.post_likes
for select
to authenticated
using (true);

drop policy if exists post_likes_insert_self on public.post_likes;
create policy post_likes_insert_self
on public.post_likes
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists post_likes_delete_self on public.post_likes;
create policy post_likes_delete_self
on public.post_likes
for delete
to authenticated
using (user_id = auth.uid());

-- comments
drop policy if exists comments_select_authenticated on public.comments;
create policy comments_select_authenticated
on public.comments
for select
to authenticated
using (true);

drop policy if exists comments_insert_self on public.comments;
create policy comments_insert_self
on public.comments
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists comments_update_self on public.comments;
create policy comments_update_self
on public.comments
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists comments_delete_self on public.comments;
create policy comments_delete_self
on public.comments
for delete
to authenticated
using (user_id = auth.uid());

-- messages
drop policy if exists messages_select_participants on public.messages;
create policy messages_select_participants
on public.messages
for select
to authenticated
using (sender_id = auth.uid() or receiver_id = auth.uid());

drop policy if exists messages_insert_sender on public.messages;
create policy messages_insert_sender
on public.messages
for insert
to authenticated
with check (sender_id = auth.uid());

drop policy if exists messages_delete_participants on public.messages;
create policy messages_delete_participants
on public.messages
for delete
to authenticated
using (sender_id = auth.uid() or receiver_id = auth.uid());

-- communities
drop policy if exists communities_select_authenticated on public.communities;
create policy communities_select_authenticated
on public.communities
for select
to authenticated
using (true);

drop policy if exists communities_insert_creator on public.communities;
create policy communities_insert_creator
on public.communities
for insert
to authenticated
with check (created_by = auth.uid());

drop policy if exists communities_update_creator on public.communities;
create policy communities_update_creator
on public.communities
for update
to authenticated
using (created_by = auth.uid())
with check (created_by = auth.uid());

drop policy if exists communities_delete_creator on public.communities;
create policy communities_delete_creator
on public.communities
for delete
to authenticated
using (created_by = auth.uid());

-- community_members
drop policy if exists community_members_select_authenticated on public.community_members;
create policy community_members_select_authenticated
on public.community_members
for select
to authenticated
using (true);

drop policy if exists community_members_insert_self_or_creator on public.community_members;
create policy community_members_insert_self_or_creator
on public.community_members
for insert
to authenticated
with check (
  user_id = auth.uid()
  or exists (
    select 1
    from public.communities c
    where c.id = community_id
      and c.created_by = auth.uid()
  )
);

drop policy if exists community_members_delete_self_or_creator on public.community_members;
create policy community_members_delete_self_or_creator
on public.community_members
for delete
to authenticated
using (
  user_id = auth.uid()
  or exists (
    select 1
    from public.communities c
    where c.id = community_id
      and c.created_by = auth.uid()
  )
);

-- community_posts
drop policy if exists community_posts_select_members_only on public.community_posts;
create policy community_posts_select_members_only
on public.community_posts
for select
to authenticated
using (
  exists (
    select 1
    from public.communities c
    where c.id = community_id
      and c.created_by = auth.uid()
  )
  or exists (
    select 1
    from public.community_members cm
    where cm.community_id = community_id
      and cm.user_id = auth.uid()
  )
);

drop policy if exists community_posts_insert_members_only on public.community_posts;
create policy community_posts_insert_members_only
on public.community_posts
for insert
to authenticated
with check (
  user_id = auth.uid()
  and (
    exists (
      select 1
      from public.communities c
      where c.id = community_id
        and c.created_by = auth.uid()
    )
    or exists (
      select 1
      from public.community_members cm
      where cm.community_id = community_id
        and cm.user_id = auth.uid()
    )
  )
);

drop policy if exists community_posts_update_members_only on public.community_posts;
create policy community_posts_update_members_only
on public.community_posts
for update
to authenticated
using (
  exists (
    select 1
    from public.communities c
    where c.id = community_id
      and c.created_by = auth.uid()
  )
  or exists (
    select 1
    from public.community_members cm
    where cm.community_id = community_id
      and cm.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.communities c
    where c.id = community_id
      and c.created_by = auth.uid()
  )
  or exists (
    select 1
    from public.community_members cm
    where cm.community_id = community_id
      and cm.user_id = auth.uid()
  )
);

drop policy if exists community_posts_delete_owner_or_creator on public.community_posts;
create policy community_posts_delete_owner_or_creator
on public.community_posts
for delete
to authenticated
using (
  user_id = auth.uid()
  or exists (
    select 1
    from public.communities c
    where c.id = community_id
      and c.created_by = auth.uid()
  )
);

-- playlists
drop policy if exists playlists_select_authenticated on public.playlists;
create policy playlists_select_authenticated
on public.playlists
for select
to authenticated
using (true);

drop policy if exists playlists_insert_owner on public.playlists;
create policy playlists_insert_owner
on public.playlists
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists playlists_update_owner on public.playlists;
create policy playlists_update_owner
on public.playlists
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists playlists_delete_owner on public.playlists;
create policy playlists_delete_owner
on public.playlists
for delete
to authenticated
using (user_id = auth.uid());

-- ascensao_posts
drop policy if exists ascensao_posts_select_authenticated on public.ascensao_posts;
create policy ascensao_posts_select_authenticated
on public.ascensao_posts
for select
to authenticated
using (true);

drop policy if exists ascensao_posts_insert_owner on public.ascensao_posts;
create policy ascensao_posts_insert_owner
on public.ascensao_posts
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists ascensao_posts_update_authenticated on public.ascensao_posts;
create policy ascensao_posts_update_authenticated
on public.ascensao_posts
for update
to authenticated
using (true)
with check (true);

drop policy if exists ascensao_posts_delete_owner on public.ascensao_posts;
create policy ascensao_posts_delete_owner
on public.ascensao_posts
for delete
to authenticated
using (user_id = auth.uid());

-- user_follows
drop policy if exists user_follows_select_authenticated on public.user_follows;
create policy user_follows_select_authenticated
on public.user_follows
for select
to authenticated
using (true);

drop policy if exists user_follows_insert_follower on public.user_follows;
create policy user_follows_insert_follower
on public.user_follows
for insert
to authenticated
with check (follower_id = auth.uid() and follower_id <> following_id);

drop policy if exists user_follows_delete_follower on public.user_follows;
create policy user_follows_delete_follower
on public.user_follows
for delete
to authenticated
using (follower_id = auth.uid());

-- =====================================================
-- Storage bucket (media)
-- =====================================================
insert into storage.buckets (id, name, public)
values ('media', 'media', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists media_public_read on storage.objects;
create policy media_public_read
on storage.objects
for select
to public
using (bucket_id = 'media');

drop policy if exists media_auth_insert on storage.objects;
create policy media_auth_insert
on storage.objects
for insert
to authenticated
with check (bucket_id = 'media');

drop policy if exists media_auth_update on storage.objects;
create policy media_auth_update
on storage.objects
for update
to authenticated
using (bucket_id = 'media')
with check (bucket_id = 'media');

drop policy if exists media_auth_delete on storage.objects;
create policy media_auth_delete
on storage.objects
for delete
to authenticated
using (bucket_id = 'media');

-- =====================================================
-- Grants (safe defaults)
-- =====================================================
grant usage on schema public to anon, authenticated;
grant all on all tables in schema public to anon, authenticated;
grant all on all sequences in schema public to anon, authenticated;
alter default privileges in schema public grant all on tables to anon, authenticated;
alter default privileges in schema public grant all on sequences to anon, authenticated;
