-- Sonora - Full Supabase schema
-- Apply in Supabase SQL Editor (new project / clean schema recommended).

-- =====================================================
-- Extensions
-- =====================================================
create extension if not exists pgcrypto;

-- =====================================================
-- Utility function for updated_at
-- =====================================================
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.media_object_belongs_to_user(object_name text)
returns boolean
language sql
stable
as $$
  select
    split_part(object_name, '/', 1) = auth.uid()::text
    or split_part(object_name, '/', 2) = auth.uid()::text;
$$;

-- =====================================================
-- Core tables
-- =====================================================
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  handle text not null,
  bio text,
  avatar_url text,
  cover_url text,
  spotify_capsule jsonb,
  spotify_capsule_updated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_handle_format check (left(handle, 1) = '@'),
  constraint profiles_spotify_capsule_is_object check (
    spotify_capsule is null or jsonb_typeof(spotify_capsule) = 'object'
  )
);

alter table if exists public.profiles
  add column if not exists spotify_capsule jsonb;

alter table if exists public.profiles
  add column if not exists spotify_capsule_updated_at timestamptz;

create unique index if not exists profiles_handle_unique_ci
  on public.profiles (lower(handle));

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  content text,
  spotify_url text,
  spotify_type text,
  media_url text,
  media_type text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists posts_user_id_created_at_idx
  on public.posts (user_id, created_at desc);

create table if not exists public.post_likes (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint post_likes_unique unique (post_id, user_id)
);

create index if not exists post_likes_user_id_idx
  on public.post_likes (user_id);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists comments_post_id_created_at_idx
  on public.comments (post_id, created_at asc);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now(),
  constraint messages_sender_receiver_diff check (sender_id <> receiver_id)
);

create index if not exists messages_sender_receiver_created_idx
  on public.messages (sender_id, receiver_id, created_at desc);

create index if not exists messages_receiver_sender_created_idx
  on public.messages (receiver_id, sender_id, created_at desc);

create table if not exists public.communities (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text,
  rules text,
  created_by uuid not null references public.profiles(id) on delete cascade,
  genre text,
  is_public boolean not null default true,
  avatar_url text,
  cover_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists communities_created_by_idx
  on public.communities (created_by);

alter table if exists public.communities
  add column if not exists rules text;

alter table if exists public.communities
  add column if not exists genre text;

alter table if exists public.communities
  add column if not exists is_public boolean not null default true;

alter table if exists public.communities
  add column if not exists avatar_url text;

alter table if exists public.communities
  add column if not exists cover_url text;

alter table if exists public.communities
  add column if not exists created_at timestamptz not null default now();

alter table if exists public.communities
  add column if not exists updated_at timestamptz not null default now();

create table if not exists public.community_members (
  id bigint generated by default as identity primary key,
  community_id uuid not null references public.communities(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'member',
  status text not null default 'approved',
  approved_by uuid references public.profiles(id) on delete set null,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint community_members_role_check check (role in ('owner', 'admin', 'mod', 'member')),
  constraint community_members_status_check check (status in ('pending', 'approved', 'rejected')),
  constraint community_members_unique unique (community_id, user_id)
);

alter table if exists public.community_members
  add column if not exists role text not null default 'member';

alter table if exists public.community_members
  add column if not exists status text not null default 'approved';

alter table if exists public.community_members
  add column if not exists approved_by uuid references public.profiles(id) on delete set null;

alter table if exists public.community_members
  add column if not exists approved_at timestamptz;

alter table if exists public.community_members
  add column if not exists updated_at timestamptz not null default now();

update public.community_members
set role = 'member'
where role is null or role not in ('owner', 'admin', 'mod', 'member');

update public.community_members
set status = 'approved'
where status is null or status not in ('pending', 'approved', 'rejected');

alter table if exists public.community_members
  drop constraint if exists community_members_role_check;

alter table if exists public.community_members
  add constraint community_members_role_check check (role in ('owner', 'admin', 'mod', 'member'));

alter table if exists public.community_members
  drop constraint if exists community_members_status_check;

alter table if exists public.community_members
  add constraint community_members_status_check check (status in ('pending', 'approved', 'rejected'));

create index if not exists community_members_user_idx
  on public.community_members (user_id);

create index if not exists community_members_community_status_idx
  on public.community_members (community_id, status, created_at desc);

create index if not exists community_members_community_role_status_idx
  on public.community_members (community_id, role, status);

create or replace function public.is_community_owner(community uuid, user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.communities c
    where c.id = community
      and c.created_by = user_id
  );
$$;

create or replace function public.is_community_approved_member(community uuid, user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    public.is_community_owner(community, user_id)
    or exists (
      select 1
      from public.community_members cm
      where cm.community_id = community
        and cm.user_id = user_id
        and cm.status = 'approved'
    );
$$;

create or replace function public.is_community_manager(community uuid, user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    public.is_community_owner(community, user_id)
    or exists (
      select 1
      from public.community_members cm
      where cm.community_id = community
        and cm.user_id = user_id
        and cm.status = 'approved'
        and cm.role in ('admin', 'mod')
    );
$$;

create or replace function public.can_edit_community_settings(community uuid, user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    public.is_community_owner(community, user_id)
    or exists (
      select 1
      from public.community_members cm
      where cm.community_id = community
        and cm.user_id = user_id
        and cm.status = 'approved'
        and cm.role = 'admin'
    );
$$;

revoke all on function public.is_community_owner(uuid, uuid) from public;
revoke all on function public.is_community_approved_member(uuid, uuid) from public;
revoke all on function public.is_community_manager(uuid, uuid) from public;
revoke all on function public.can_edit_community_settings(uuid, uuid) from public;

grant execute on function public.is_community_owner(uuid, uuid) to authenticated;
grant execute on function public.is_community_approved_member(uuid, uuid) to authenticated;
grant execute on function public.is_community_manager(uuid, uuid) to authenticated;
grant execute on function public.can_edit_community_settings(uuid, uuid) to authenticated;

create table if not exists public.community_posts (
  id bigint generated by default as identity primary key,
  community_id uuid not null references public.communities(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  post_type text,
  title text,
  spotify_url text,
  image_url text,
  album text,
  track_number text,
  content text,
  likes_count integer not null default 0,
  shares_count integer not null default 0,
  saves_count integer not null default 0,
  comments jsonb not null default '[]'::jsonb,
  poll_options jsonb not null default '[]'::jsonb,
  poll_votes jsonb not null default '{}'::jsonb,
  poll_total_votes integer not null default 0,
  challenge_entries jsonb not null default '[]'::jsonb,
  challenge_unit text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint community_posts_comments_is_array check (jsonb_typeof(comments) = 'array'),
  constraint community_posts_poll_options_is_array check (jsonb_typeof(poll_options) = 'array'),
  constraint community_posts_poll_votes_is_object check (jsonb_typeof(poll_votes) = 'object'),
  constraint community_posts_challenge_entries_is_array check (jsonb_typeof(challenge_entries) = 'array')
);

create index if not exists community_posts_community_created_idx
  on public.community_posts (community_id, created_at desc);

create index if not exists community_posts_user_created_idx
  on public.community_posts (user_id, created_at desc);

create table if not exists public.playlists (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  description text,
  spotify_url text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists playlists_user_created_idx
  on public.playlists (user_id, created_at desc);

create table if not exists public.marketplace_listings (
  id bigint generated by default as identity primary key,
  seller_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  description text,
  price numeric(12,2) not null,
  currency text not null default 'BRL',
  category text,
  condition text not null default 'used',
  location text,
  purchase_url text,
  image_url text,
  image_position_x integer not null default 50,
  image_position_y integer not null default 50,
  is_active boolean not null default true,
  status text not null default 'available',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint marketplace_listings_price_non_negative check (price >= 0),
  constraint marketplace_listings_condition_check check (condition in ('new', 'used')),
  constraint marketplace_listings_status_check check (status in ('available', 'sold')),
  constraint marketplace_listings_position_x_check check (image_position_x between 0 and 100),
  constraint marketplace_listings_position_y_check check (image_position_y between 0 and 100)
);

create index if not exists marketplace_listings_seller_created_idx
  on public.marketplace_listings (seller_id, created_at desc);

create index if not exists marketplace_listings_active_created_idx
  on public.marketplace_listings (is_active, created_at desc);

create index if not exists marketplace_listings_price_idx
  on public.marketplace_listings (price);

create index if not exists marketplace_listings_location_ci_idx
  on public.marketplace_listings (lower(location));

create index if not exists marketplace_listings_category_ci_idx
  on public.marketplace_listings (lower(category));

alter table if exists public.marketplace_listings
  add column if not exists image_position_x integer not null default 50;

alter table if exists public.marketplace_listings
  add column if not exists image_position_y integer not null default 50;

alter table if exists public.marketplace_listings
  add column if not exists status text not null default 'available';

alter table if exists public.marketplace_listings
  drop constraint if exists marketplace_listings_status_check;

alter table if exists public.marketplace_listings
  add constraint marketplace_listings_status_check check (status in ('available', 'sold'));

create index if not exists marketplace_listings_status_created_idx
  on public.marketplace_listings (status, created_at desc);

create table if not exists public.marketplace_favorites (
  id bigint generated by default as identity primary key,
  listing_id bigint not null references public.marketplace_listings(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint marketplace_favorites_unique unique (listing_id, user_id)
);

create index if not exists marketplace_favorites_listing_idx
  on public.marketplace_favorites (listing_id);

create index if not exists marketplace_favorites_user_created_idx
  on public.marketplace_favorites (user_id, created_at desc);

create table if not exists public.marketplace_chat_messages (
  id bigint generated by default as identity primary key,
  listing_id bigint not null references public.marketplace_listings(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now(),
  constraint marketplace_chat_messages_sender_receiver_diff check (sender_id <> receiver_id)
);

create index if not exists marketplace_chat_messages_listing_created_idx
  on public.marketplace_chat_messages (listing_id, created_at asc);

create index if not exists marketplace_chat_messages_sender_receiver_created_idx
  on public.marketplace_chat_messages (sender_id, receiver_id, created_at desc);

create index if not exists marketplace_chat_messages_receiver_sender_created_idx
  on public.marketplace_chat_messages (receiver_id, sender_id, created_at desc);

create table if not exists public.music_events (
  id bigint generated by default as identity primary key,
  organizer_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  description text,
  event_date timestamptz not null,
  venue text not null,
  city text not null,
  genre text,
  ticket_url text,
  contact_url text,
  needs_artists boolean not null default false,
  artist_requirements text,
  cover_url text,
  cover_position_x integer not null default 50,
  cover_position_y integer not null default 50,
  event_timezone text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint music_events_cover_position_x_check check (cover_position_x between 0 and 100),
  constraint music_events_cover_position_y_check check (cover_position_y between 0 and 100)
);

create index if not exists music_events_date_idx
  on public.music_events (event_date asc);

create index if not exists music_events_organizer_created_idx
  on public.music_events (organizer_id, created_at desc);

alter table if exists public.music_events
  add column if not exists cover_position_x integer not null default 50;

alter table if exists public.music_events
  add column if not exists cover_position_y integer not null default 50;

alter table if exists public.music_events
  add column if not exists event_timezone text;

create table if not exists public.event_rsvps (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.music_events(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'going',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint event_rsvps_unique unique (event_id, user_id),
  constraint event_rsvps_status_check check (status in ('going'))
);

create index if not exists event_rsvps_event_created_idx
  on public.event_rsvps (event_id, created_at asc);

create index if not exists event_rsvps_user_created_idx
  on public.event_rsvps (user_id, created_at desc);

create table if not exists public.event_artist_applications (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.music_events(id) on delete cascade,
  artist_id uuid not null references public.profiles(id) on delete cascade,
  message text,
  portfolio_url text,
  status text not null default 'pending',
  reviewed_at timestamptz,
  reviewed_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint event_artist_applications_unique unique (event_id, artist_id),
  constraint event_artist_applications_status_check check (status in ('pending', 'accepted', 'rejected'))
);

create index if not exists event_artist_applications_event_created_idx
  on public.event_artist_applications (event_id, created_at desc);

create index if not exists event_artist_applications_artist_created_idx
  on public.event_artist_applications (artist_id, created_at desc);

create table if not exists public.ascensao_posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text,
  content text,
  post_kind text not null default 'video',
  media_url text not null,
  likes_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ascensao_posts_kind_check check (post_kind in ('video', 'audio', 'youtube'))
);

create index if not exists ascensao_posts_user_created_idx
  on public.ascensao_posts (user_id, created_at desc);

create table if not exists public.user_follows (
  id bigint generated by default as identity primary key,
  follower_id uuid not null references public.profiles(id) on delete cascade,
  following_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint user_follows_unique unique (follower_id, following_id),
  constraint user_follows_diff check (follower_id <> following_id)
);

create index if not exists user_follows_follower_idx
  on public.user_follows (follower_id);

create index if not exists user_follows_following_idx
  on public.user_follows (following_id);

create table if not exists public.user_blocks (
  id bigint generated by default as identity primary key,
  blocker_id uuid not null references public.profiles(id) on delete cascade,
  blocked_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint user_blocks_unique unique (blocker_id, blocked_id),
  constraint user_blocks_diff check (blocker_id <> blocked_id)
);

create index if not exists user_blocks_blocker_idx
  on public.user_blocks (blocker_id);

create index if not exists user_blocks_blocked_idx
  on public.user_blocks (blocked_id);

create table if not exists public.moderation_reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  reported_user_id uuid references public.profiles(id) on delete set null,
  target_type text not null,
  target_post_id text,
  target_profile_id text,
  target_listing_id text,
  reason text not null,
  details text,
  created_at timestamptz not null default now(),
  constraint moderation_reports_target_type_check check (
    target_type in ('post', 'profile', 'listing')
  ),
  constraint moderation_reports_exactly_one_target check (
    (
      case when target_post_id is not null then 1 else 0 end
      + case when target_profile_id is not null then 1 else 0 end
      + case when target_listing_id is not null then 1 else 0 end
    ) = 1
  ),
  constraint moderation_reports_target_matches_type check (
    (target_type = 'post' and target_post_id is not null and target_profile_id is null and target_listing_id is null)
    or (target_type = 'profile' and target_post_id is null and target_profile_id is not null and target_listing_id is null)
    or (target_type = 'listing' and target_post_id is null and target_profile_id is null and target_listing_id is not null)
  )
);

create index if not exists moderation_reports_reporter_created_idx
  on public.moderation_reports (reporter_id, created_at desc);

create index if not exists moderation_reports_target_type_idx
  on public.moderation_reports (target_type, created_at desc);

create unique index if not exists moderation_reports_unique_post
  on public.moderation_reports (reporter_id, target_post_id)
  where target_post_id is not null;

create unique index if not exists moderation_reports_unique_profile
  on public.moderation_reports (reporter_id, target_profile_id)
  where target_profile_id is not null;

create unique index if not exists moderation_reports_unique_listing
  on public.moderation_reports (reporter_id, target_listing_id)
  where target_listing_id is not null;

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  type text not null,
  title text not null,
  body text,
  entity_type text,
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  is_read boolean not null default false,
  created_at timestamptz not null default now(),
  constraint notifications_type_check check (
    type in ('like', 'comment', 'follow', 'community_invite', 'message', 'event_new')
  ),
  constraint notifications_entity_type_check check (
    entity_type is null or entity_type in ('post', 'profile', 'community', 'message', 'event')
  ),
  constraint notifications_metadata_object_check check (jsonb_typeof(metadata) = 'object')
);

create index if not exists notifications_recipient_created_idx
  on public.notifications (recipient_id, created_at desc);

create index if not exists notifications_recipient_unread_idx
  on public.notifications (recipient_id, is_read, created_at desc);

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  endpoint text not null,
  p256dh text not null,
  auth text not null,
  user_agent text,
  enabled boolean not null default true,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table if exists public.push_subscriptions
  add column if not exists user_id uuid references public.profiles(id) on delete cascade;

alter table if exists public.push_subscriptions
  add column if not exists endpoint text;

alter table if exists public.push_subscriptions
  add column if not exists p256dh text;

alter table if exists public.push_subscriptions
  add column if not exists auth text;

alter table if exists public.push_subscriptions
  add column if not exists user_agent text;

alter table if exists public.push_subscriptions
  add column if not exists enabled boolean not null default true;

alter table if exists public.push_subscriptions
  add column if not exists last_seen_at timestamptz not null default now();

alter table if exists public.push_subscriptions
  add column if not exists created_at timestamptz not null default now();

alter table if exists public.push_subscriptions
  add column if not exists updated_at timestamptz not null default now();

create unique index if not exists push_subscriptions_user_endpoint_unique_idx
  on public.push_subscriptions (user_id, endpoint);

create index if not exists push_subscriptions_user_enabled_idx
  on public.push_subscriptions (user_id, enabled, updated_at desc);

-- Compatibility for projects where target table IDs may be uuid/bigint.
-- We keep report target IDs as text to avoid FK type conflicts.
alter table if exists public.moderation_reports
  drop constraint if exists moderation_reports_target_post_id_fkey;

alter table if exists public.moderation_reports
  drop constraint if exists moderation_reports_target_profile_id_fkey;

alter table if exists public.moderation_reports
  drop constraint if exists moderation_reports_target_listing_id_fkey;

alter table if exists public.moderation_reports
  alter column target_post_id type text using target_post_id::text;

alter table if exists public.moderation_reports
  alter column target_profile_id type text using target_profile_id::text;

alter table if exists public.moderation_reports
  alter column target_listing_id type text using target_listing_id::text;

-- =====================================================
-- Triggers
-- =====================================================
drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists trg_posts_updated_at on public.posts;
create trigger trg_posts_updated_at
before update on public.posts
for each row execute function public.set_updated_at();

drop trigger if exists trg_comments_updated_at on public.comments;
create trigger trg_comments_updated_at
before update on public.comments
for each row execute function public.set_updated_at();

drop trigger if exists trg_communities_updated_at on public.communities;
create trigger trg_communities_updated_at
before update on public.communities
for each row execute function public.set_updated_at();

drop trigger if exists trg_community_members_updated_at on public.community_members;
create trigger trg_community_members_updated_at
before update on public.community_members
for each row execute function public.set_updated_at();

drop trigger if exists trg_community_posts_updated_at on public.community_posts;
create trigger trg_community_posts_updated_at
before update on public.community_posts
for each row execute function public.set_updated_at();

drop trigger if exists trg_playlists_updated_at on public.playlists;
create trigger trg_playlists_updated_at
before update on public.playlists
for each row execute function public.set_updated_at();

drop trigger if exists trg_marketplace_listings_updated_at on public.marketplace_listings;
create trigger trg_marketplace_listings_updated_at
before update on public.marketplace_listings
for each row execute function public.set_updated_at();

drop trigger if exists trg_music_events_updated_at on public.music_events;
create trigger trg_music_events_updated_at
before update on public.music_events
for each row execute function public.set_updated_at();

drop trigger if exists trg_event_rsvps_updated_at on public.event_rsvps;
create trigger trg_event_rsvps_updated_at
before update on public.event_rsvps
for each row execute function public.set_updated_at();

drop trigger if exists trg_event_artist_applications_updated_at on public.event_artist_applications;
create trigger trg_event_artist_applications_updated_at
before update on public.event_artist_applications
for each row execute function public.set_updated_at();

drop trigger if exists trg_ascensao_posts_updated_at on public.ascensao_posts;
create trigger trg_ascensao_posts_updated_at
before update on public.ascensao_posts
for each row execute function public.set_updated_at();

drop trigger if exists trg_push_subscriptions_updated_at on public.push_subscriptions;
create trigger trg_push_subscriptions_updated_at
before update on public.push_subscriptions
for each row execute function public.set_updated_at();

-- =====================================================
-- Realtime publication (needed by feed/direct/playlists live updates)
-- =====================================================
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'posts') then
      execute 'alter publication supabase_realtime add table public.posts';
    end if;
    if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'messages') then
      execute 'alter publication supabase_realtime add table public.messages';
    end if;
    if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'communities') then
      execute 'alter publication supabase_realtime add table public.communities';
    end if;
    if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'community_members') then
      execute 'alter publication supabase_realtime add table public.community_members';
    end if;
    if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'playlists') then
      execute 'alter publication supabase_realtime add table public.playlists';
    end if;
    if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'notifications') then
      execute 'alter publication supabase_realtime add table public.notifications';
    end if;
    if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'marketplace_chat_messages') then
      execute 'alter publication supabase_realtime add table public.marketplace_chat_messages';
    end if;
  end if;
end $$;

-- =====================================================
-- RLS
-- =====================================================
alter table public.profiles enable row level security;
alter table public.posts enable row level security;
alter table public.post_likes enable row level security;
alter table public.comments enable row level security;
alter table public.messages enable row level security;
alter table public.communities enable row level security;
alter table public.community_members enable row level security;
alter table public.community_posts enable row level security;
alter table public.playlists enable row level security;
alter table public.marketplace_listings enable row level security;
alter table public.marketplace_favorites enable row level security;
alter table public.marketplace_chat_messages enable row level security;
alter table public.music_events enable row level security;
alter table public.event_rsvps enable row level security;
alter table public.event_artist_applications enable row level security;
alter table public.ascensao_posts enable row level security;
alter table public.user_follows enable row level security;
alter table public.user_blocks enable row level security;
alter table public.moderation_reports enable row level security;
alter table public.notifications enable row level security;
alter table public.push_subscriptions enable row level security;

-- profiles
drop policy if exists profiles_select_authenticated on public.profiles;
create policy profiles_select_authenticated
on public.profiles
for select
to authenticated
using (true);

drop policy if exists profiles_insert_self on public.profiles;
create policy profiles_insert_self
on public.profiles
for insert
to authenticated
with check (id = auth.uid());

drop policy if exists profiles_update_self on public.profiles;
create policy profiles_update_self
on public.profiles
for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

drop policy if exists profiles_delete_self on public.profiles;
create policy profiles_delete_self
on public.profiles
for delete
to authenticated
using (id = auth.uid());

-- posts
drop policy if exists posts_select_authenticated on public.posts;
create policy posts_select_authenticated
on public.posts
for select
to authenticated
using (true);

drop policy if exists posts_insert_owner on public.posts;
create policy posts_insert_owner
on public.posts
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists posts_update_owner on public.posts;
create policy posts_update_owner
on public.posts
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists posts_delete_owner on public.posts;
create policy posts_delete_owner
on public.posts
for delete
to authenticated
using (user_id = auth.uid());

-- post_likes
drop policy if exists post_likes_select_authenticated on public.post_likes;
create policy post_likes_select_authenticated
on public.post_likes
for select
to authenticated
using (true);

drop policy if exists post_likes_insert_self on public.post_likes;
create policy post_likes_insert_self
on public.post_likes
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists post_likes_delete_self on public.post_likes;
create policy post_likes_delete_self
on public.post_likes
for delete
to authenticated
using (user_id = auth.uid());

-- comments
drop policy if exists comments_select_authenticated on public.comments;
create policy comments_select_authenticated
on public.comments
for select
to authenticated
using (true);

drop policy if exists comments_insert_self on public.comments;
create policy comments_insert_self
on public.comments
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists comments_update_self on public.comments;
create policy comments_update_self
on public.comments
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists comments_delete_self on public.comments;
create policy comments_delete_self
on public.comments
for delete
to authenticated
using (user_id = auth.uid());

-- messages
drop policy if exists messages_select_participants on public.messages;
create policy messages_select_participants
on public.messages
for select
to authenticated
using (sender_id = auth.uid() or receiver_id = auth.uid());

drop policy if exists messages_insert_sender on public.messages;
create policy messages_insert_sender
on public.messages
for insert
to authenticated
with check (sender_id = auth.uid());

drop policy if exists messages_delete_participants on public.messages;
create policy messages_delete_participants
on public.messages
for delete
to authenticated
using (sender_id = auth.uid() or receiver_id = auth.uid());

-- communities
drop policy if exists communities_select_authenticated on public.communities;
create policy communities_select_authenticated
on public.communities
for select
to authenticated
using (true);

drop policy if exists communities_insert_creator on public.communities;
create policy communities_insert_creator
on public.communities
for insert
to authenticated
with check (created_by = auth.uid());

drop policy if exists communities_update_manager on public.communities;
drop policy if exists communities_update_creator on public.communities;
create policy communities_update_manager
on public.communities
for update
to authenticated
using (public.can_edit_community_settings(id))
with check (public.can_edit_community_settings(id));

drop policy if exists communities_delete_creator on public.communities;
create policy communities_delete_creator
on public.communities
for delete
to authenticated
using (public.is_community_owner(id));

-- community_members
drop policy if exists community_members_select_visible on public.community_members;
drop policy if exists community_members_select_authenticated on public.community_members;
create policy community_members_select_visible
on public.community_members
for select
to authenticated
using (
  status = 'approved'
  or user_id = auth.uid()
  or public.is_community_manager(community_id)
);

drop policy if exists community_members_insert_self_request on public.community_members;
drop policy if exists community_members_insert_self_or_creator on public.community_members;
create policy community_members_insert_self_request
on public.community_members
for insert
to authenticated
with check (
  user_id = auth.uid()
  and role = 'member'
  and (
    (
      status = 'approved'
      and exists (
        select 1
        from public.communities c
        where c.id = community_id
          and c.is_public = true
      )
    )
    or (
      status = 'pending'
      and exists (
        select 1
        from public.communities c
        where c.id = community_id
          and c.is_public = false
      )
    )
  )
);

drop policy if exists community_members_insert_manager on public.community_members;
create policy community_members_insert_manager
on public.community_members
for insert
to authenticated
with check (
  public.can_edit_community_settings(community_id)
  and role in ('member', 'admin', 'mod')
  and status in ('pending', 'approved', 'rejected')
);

drop policy if exists community_members_update_owner_admin on public.community_members;
drop policy if exists community_members_update_manager on public.community_members;
create policy community_members_update_owner_admin
on public.community_members
for update
to authenticated
using (public.can_edit_community_settings(community_id))
with check (
  public.can_edit_community_settings(community_id)
  and role in ('member', 'admin', 'mod')
  and status in ('pending', 'approved', 'rejected')
);

drop policy if exists community_members_update_mod_queue on public.community_members;
create policy community_members_update_mod_queue
on public.community_members
for update
to authenticated
using (
  public.is_community_manager(community_id)
  and not public.can_edit_community_settings(community_id)
  and status = 'pending'
)
with check (
  public.is_community_manager(community_id)
  and not public.can_edit_community_settings(community_id)
  and role = 'member'
  and status in ('pending', 'approved', 'rejected')
);

drop policy if exists community_members_delete_self_or_owner_admin_or_mod on public.community_members;
drop policy if exists community_members_delete_self_or_manager on public.community_members;
drop policy if exists community_members_delete_self_or_creator on public.community_members;
create policy community_members_delete_self_or_owner_admin_or_mod
on public.community_members
for delete
to authenticated
using (
  user_id = auth.uid()
  or (
    public.can_edit_community_settings(community_id)
    and not public.is_community_owner(community_id, user_id)
  )
  or (
    public.is_community_manager(community_id)
    and not public.can_edit_community_settings(community_id)
    and status = 'pending'
  )
);

-- community_posts
drop policy if exists community_posts_select_members_only on public.community_posts;
create policy community_posts_select_members_only
on public.community_posts
for select
to authenticated
using (public.is_community_approved_member(community_id));

drop policy if exists community_posts_insert_members_only on public.community_posts;
create policy community_posts_insert_members_only
on public.community_posts
for insert
to authenticated
with check (
  user_id = auth.uid()
  and public.is_community_approved_member(community_id)
);

drop policy if exists community_posts_update_owner_or_manager on public.community_posts;
drop policy if exists community_posts_update_members_only on public.community_posts;
create policy community_posts_update_owner_or_manager
on public.community_posts
for update
to authenticated
using (
  user_id = auth.uid()
  or public.is_community_manager(community_id)
)
with check (
  user_id = auth.uid()
  or public.is_community_manager(community_id)
);

drop policy if exists community_posts_delete_owner_or_creator on public.community_posts;
drop policy if exists community_posts_delete_owner_or_manager on public.community_posts;
create policy community_posts_delete_owner_or_manager
on public.community_posts
for delete
to authenticated
using (
  user_id = auth.uid()
  or public.is_community_manager(community_id)
);

-- playlists
drop policy if exists playlists_select_authenticated on public.playlists;
create policy playlists_select_authenticated
on public.playlists
for select
to authenticated
using (true);

drop policy if exists playlists_insert_owner on public.playlists;
create policy playlists_insert_owner
on public.playlists
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists playlists_update_owner on public.playlists;
create policy playlists_update_owner
on public.playlists
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists playlists_delete_owner on public.playlists;
create policy playlists_delete_owner
on public.playlists
for delete
to authenticated
using (user_id = auth.uid());

-- marketplace_listings
drop policy if exists marketplace_listings_select_authenticated on public.marketplace_listings;
create policy marketplace_listings_select_authenticated
on public.marketplace_listings
for select
to authenticated
using (true);

drop policy if exists marketplace_listings_insert_owner on public.marketplace_listings;
create policy marketplace_listings_insert_owner
on public.marketplace_listings
for insert
to authenticated
with check (seller_id = auth.uid());

drop policy if exists marketplace_listings_update_owner on public.marketplace_listings;
create policy marketplace_listings_update_owner
on public.marketplace_listings
for update
to authenticated
using (seller_id = auth.uid())
with check (seller_id = auth.uid());

drop policy if exists marketplace_listings_delete_owner on public.marketplace_listings;
create policy marketplace_listings_delete_owner
on public.marketplace_listings
for delete
to authenticated
using (seller_id = auth.uid());

-- marketplace_favorites
drop policy if exists marketplace_favorites_select_authenticated on public.marketplace_favorites;
create policy marketplace_favorites_select_authenticated
on public.marketplace_favorites
for select
to authenticated
using (true);

drop policy if exists marketplace_favorites_insert_owner on public.marketplace_favorites;
create policy marketplace_favorites_insert_owner
on public.marketplace_favorites
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists marketplace_favorites_delete_owner on public.marketplace_favorites;
create policy marketplace_favorites_delete_owner
on public.marketplace_favorites
for delete
to authenticated
using (user_id = auth.uid());

-- marketplace_chat_messages
drop policy if exists marketplace_chat_messages_select_participants on public.marketplace_chat_messages;
create policy marketplace_chat_messages_select_participants
on public.marketplace_chat_messages
for select
to authenticated
using (sender_id = auth.uid() or receiver_id = auth.uid());

drop policy if exists marketplace_chat_messages_insert_sender on public.marketplace_chat_messages;
create policy marketplace_chat_messages_insert_sender
on public.marketplace_chat_messages
for insert
to authenticated
with check (
  sender_id = auth.uid()
  and sender_id <> receiver_id
  and exists (
    select 1
    from public.marketplace_listings ml
    where ml.id = listing_id
      and (ml.seller_id = sender_id or ml.seller_id = receiver_id)
  )
);

drop policy if exists marketplace_chat_messages_delete_participants on public.marketplace_chat_messages;
create policy marketplace_chat_messages_delete_participants
on public.marketplace_chat_messages
for delete
to authenticated
using (sender_id = auth.uid() or receiver_id = auth.uid());

-- music_events
drop policy if exists music_events_select_authenticated on public.music_events;
create policy music_events_select_authenticated
on public.music_events
for select
to authenticated
using (true);

drop policy if exists music_events_insert_owner on public.music_events;
create policy music_events_insert_owner
on public.music_events
for insert
to authenticated
with check (organizer_id = auth.uid());

drop policy if exists music_events_update_owner on public.music_events;
create policy music_events_update_owner
on public.music_events
for update
to authenticated
using (organizer_id = auth.uid())
with check (organizer_id = auth.uid());

drop policy if exists music_events_delete_owner on public.music_events;
create policy music_events_delete_owner
on public.music_events
for delete
to authenticated
using (organizer_id = auth.uid());

-- event_rsvps
drop policy if exists event_rsvps_select_authenticated on public.event_rsvps;
create policy event_rsvps_select_authenticated
on public.event_rsvps
for select
to authenticated
using (true);

drop policy if exists event_rsvps_insert_self on public.event_rsvps;
create policy event_rsvps_insert_self
on public.event_rsvps
for insert
to authenticated
with check (user_id = auth.uid() and status = 'going');

drop policy if exists event_rsvps_update_self on public.event_rsvps;
create policy event_rsvps_update_self
on public.event_rsvps
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid() and status = 'going');

drop policy if exists event_rsvps_delete_self on public.event_rsvps;
create policy event_rsvps_delete_self
on public.event_rsvps
for delete
to authenticated
using (user_id = auth.uid());

-- event_artist_applications
drop policy if exists event_artist_applications_select_member_or_organizer on public.event_artist_applications;
create policy event_artist_applications_select_member_or_organizer
on public.event_artist_applications
for select
to authenticated
using (
  artist_id = auth.uid()
  or exists (
    select 1
    from public.music_events me
    where me.id = event_id
      and me.organizer_id = auth.uid()
  )
);

drop policy if exists event_artist_applications_insert_artist on public.event_artist_applications;
create policy event_artist_applications_insert_artist
on public.event_artist_applications
for insert
to authenticated
with check (
  artist_id = auth.uid()
  and exists (
    select 1
    from public.music_events me
    where me.id = event_id
      and me.needs_artists = true
  )
);

drop policy if exists event_artist_applications_update_artist on public.event_artist_applications;
create policy event_artist_applications_update_artist
on public.event_artist_applications
for update
to authenticated
using (artist_id = auth.uid())
with check (
  artist_id = auth.uid()
  and status = 'pending'
  and reviewed_at is null
  and reviewed_by is null
);

drop policy if exists event_artist_applications_update_artist_or_organizer on public.event_artist_applications;
drop policy if exists event_artist_applications_update_organizer on public.event_artist_applications;
create policy event_artist_applications_update_organizer
on public.event_artist_applications
for update
to authenticated
using (
  exists (
    select 1
    from public.music_events me
    where me.id = event_id
      and me.organizer_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.music_events me
    where me.id = event_id
      and me.organizer_id = auth.uid()
  )
);

drop policy if exists event_artist_applications_delete_artist_or_organizer on public.event_artist_applications;
create policy event_artist_applications_delete_artist_or_organizer
on public.event_artist_applications
for delete
to authenticated
using (
  artist_id = auth.uid()
  or exists (
    select 1
    from public.music_events me
    where me.id = event_id
      and me.organizer_id = auth.uid()
  )
);

-- ascensao_posts
drop policy if exists ascensao_posts_select_authenticated on public.ascensao_posts;
create policy ascensao_posts_select_authenticated
on public.ascensao_posts
for select
to authenticated
using (true);

drop policy if exists ascensao_posts_insert_owner on public.ascensao_posts;
create policy ascensao_posts_insert_owner
on public.ascensao_posts
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists ascensao_posts_update_authenticated on public.ascensao_posts;
create policy ascensao_posts_update_authenticated
on public.ascensao_posts
for update
to authenticated
using (true)
with check (true);

drop policy if exists ascensao_posts_delete_owner on public.ascensao_posts;
create policy ascensao_posts_delete_owner
on public.ascensao_posts
for delete
to authenticated
using (user_id = auth.uid());

-- user_follows
drop policy if exists user_follows_select_authenticated on public.user_follows;
create policy user_follows_select_authenticated
on public.user_follows
for select
to authenticated
using (true);

drop policy if exists user_follows_insert_follower on public.user_follows;
create policy user_follows_insert_follower
on public.user_follows
for insert
to authenticated
with check (follower_id = auth.uid() and follower_id <> following_id);

drop policy if exists user_follows_delete_follower on public.user_follows;
create policy user_follows_delete_follower
on public.user_follows
for delete
to authenticated
using (follower_id = auth.uid());

-- user_blocks
drop policy if exists user_blocks_select_owner on public.user_blocks;
create policy user_blocks_select_owner
on public.user_blocks
for select
to authenticated
using (blocker_id = auth.uid());

drop policy if exists user_blocks_insert_owner on public.user_blocks;
create policy user_blocks_insert_owner
on public.user_blocks
for insert
to authenticated
with check (blocker_id = auth.uid() and blocker_id <> blocked_id);

drop policy if exists user_blocks_delete_owner on public.user_blocks;
create policy user_blocks_delete_owner
on public.user_blocks
for delete
to authenticated
using (blocker_id = auth.uid());

-- moderation_reports
drop policy if exists moderation_reports_select_owner on public.moderation_reports;
create policy moderation_reports_select_owner
on public.moderation_reports
for select
to authenticated
using (reporter_id = auth.uid());

drop policy if exists moderation_reports_insert_owner on public.moderation_reports;
create policy moderation_reports_insert_owner
on public.moderation_reports
for insert
to authenticated
with check (reporter_id = auth.uid());

-- notifications
drop policy if exists notifications_select_recipient on public.notifications;
drop policy if exists notifications_select_recipient_or_actor on public.notifications;
create policy notifications_select_recipient_or_actor
on public.notifications
for select
to authenticated
using (
  recipient_id = auth.uid()
  or actor_id = auth.uid()
);

drop policy if exists notifications_insert_actor on public.notifications;
create policy notifications_insert_actor
on public.notifications
for insert
to authenticated
with check (
  actor_id = auth.uid()
  and recipient_id <> auth.uid()
);

drop policy if exists notifications_update_recipient on public.notifications;
create policy notifications_update_recipient
on public.notifications
for update
to authenticated
using (recipient_id = auth.uid())
with check (recipient_id = auth.uid());

drop policy if exists notifications_delete_recipient on public.notifications;
create policy notifications_delete_recipient
on public.notifications
for delete
to authenticated
using (recipient_id = auth.uid());

-- push_subscriptions
drop policy if exists push_subscriptions_select_owner on public.push_subscriptions;
create policy push_subscriptions_select_owner
on public.push_subscriptions
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists push_subscriptions_insert_owner on public.push_subscriptions;
create policy push_subscriptions_insert_owner
on public.push_subscriptions
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists push_subscriptions_update_owner on public.push_subscriptions;
create policy push_subscriptions_update_owner
on public.push_subscriptions
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists push_subscriptions_delete_owner on public.push_subscriptions;
create policy push_subscriptions_delete_owner
on public.push_subscriptions
for delete
to authenticated
using (user_id = auth.uid());

-- =====================================================
-- Storage bucket (media)
-- =====================================================
insert into storage.buckets (id, name, public)
values ('media', 'media', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists media_public_read on storage.objects;
create policy media_public_read
on storage.objects
for select
to public
using (bucket_id = 'media');

drop policy if exists media_auth_insert on storage.objects;
create policy media_auth_insert
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'media'
  and public.media_object_belongs_to_user(name)
);

drop policy if exists media_auth_update on storage.objects;
create policy media_auth_update
on storage.objects
for update
to authenticated
using (
  bucket_id = 'media'
  and public.media_object_belongs_to_user(name)
)
with check (
  bucket_id = 'media'
  and public.media_object_belongs_to_user(name)
);

drop policy if exists media_auth_delete on storage.objects;
create policy media_auth_delete
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'media'
  and public.media_object_belongs_to_user(name)
);

-- =====================================================
-- Grants (safe defaults)
-- =====================================================
grant usage on schema public to anon, authenticated;

revoke all on all tables in schema public from anon;
revoke all on all sequences in schema public from anon;
revoke all on all tables in schema public from authenticated;
revoke all on all sequences in schema public from authenticated;

grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;

alter default privileges in schema public revoke all on tables from anon, authenticated;
alter default privileges in schema public revoke all on sequences from anon, authenticated;
alter default privileges in schema public grant select, insert, update, delete on tables to authenticated;
alter default privileges in schema public grant usage, select on sequences to authenticated;
